# Generated by Django 5.0.6 on 2024-06-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.CharField(default='default.jpg', max_length=20),
            preserve_default=False,
        ),
    ]
