# Generated by Django 5.0.6 on 2024-06-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.CharField(default='default.jpg', max_length=20),
        ),
    ]
